---
- name: Desplegar Wordpress con roles
  hosts: servers
  become: true
  gather_facts: yes
  vars_files:
  - group_vars/all/vault.yml

  roles:
    - apache
    - php
    - mariadb
    - wordpress
